### PR TITLE
Migrate dropbox strategy to oauth2.

### PR DESCRIPTION
**Pull request by francois2metz**

### CODE REVIEW

**Comment by francois2metz** [comment]
Should fix #4 and #5

**Comment by francois2metz** [comment]
I finally fixed the build for node 0.6 and 0.8. 0.4 seems broken when installing node.

**Comment by francois2metz** [comment]
@jaredhanson Any chance to merge it?

**Comment by jaredhanson** [comment]
OAuth 2.0 is available as a separate strategy: [passport-dropbox-oauth2](https://github.com/florianheinemann/passport-dropbox-oauth2)

This strategy continues to support OAuth 1.0 for applications that make use of it.

**Pull request closed without merging**
